### ISSUE TITLE
App engine application resource

### ISSUE THREAD

**Issue by billinghamj** [mirakl/terraform-google-gcr-cleaner#16]
Just a quick question - I'm been trying to figure out what the app engine application is for, but can't see any obvious purpose it serves or anything it would do

Would you be able to share a bit on what it's for, and in what sort of situations it should be enabled?

Many thanks! :)

**Comment by anouarchattouna** [comment]
Hi @billinghamj, this is required for `Cloud Scheduler` as you can see in the [official documentation](https://cloud.google.com/scheduler/docs/)
> To use Cloud Scheduler your Cloud project must contain an App Engine app that is located in one of the supported regions.

Best,

**Comment by t-gebauer** [comment]
App Engine application is no longer required for Cloud Scheduler
https://cloud.google.com/scheduler/docs/release-notes#February_11_2022 

https://cloud.google.com/scheduler/docs/overview#supported_regions_by_target
> If you are not using App Engine as a target, you do not need to deploy an App Engine app, and you can disable any existing App Engine app.
