### ISSUE TITLE
Allowing set recursive for gar repository as well

### ISSUE THREAD

**Issue by zfy0701** [mirakl/terraform-google-gcr-cleaner#54]
### TL;DR

currently we are just setting `recursive` to false for gar repository
https://github.com/mirakl/terraform-google-gcr-cleaner/blob/main/locals.tf#L82

However gcr-cleaner does support this flag to true when using gar.

If you create one docker repo using GAR and have several images, recursive will be able to deal with multiple images. Otherwise you need to write multiple `gar_repositories` rule, where each point to specific docker image

so maybe just support the flag as follow
```
  gar_repositories = [
    {
      name       = "gar_name"
      recursive = true
    }
  ]
```

**Comment by christidis** [comment]
I have included the `recursive` in the PR https://github.com/mirakl/terraform-google-gcr-cleaner/pull/53 which also handles issue https://github.com/mirakl/terraform-google-gcr-cleaner/issues/52 for managing multiple GAR repositories.
